### ISSUE TITLE
Make link in label clickable

### ISSUE THREAD

**Issue by cryzed** [WestHealth/pyvis#10]
It would be nice if there was some way to keep a node's label displayed in such a way that linked elements within it could be clicked.

**Comment by boludo00** [comment]
By label do you mean the text under the node or the text rendered from on hover?

**Comment by cryzed** [comment]
Ideally both.

**Comment by boludo00** [comment]
I have played with the HTML and JS template to recreate the following:
![image](https://user-images.githubusercontent.com/8398241/40504774-16c98546-5f47-11e8-8fd0-76532da398ee.png)

It looks clunky, but it works.

**Comment by paritoshk** [comment]
How can I use this functionality? I want users to click on the node (or hypertext Label) and get redirected to another tab within my streamlit app. Thanks!

**Comment by jasotamame** [comment]
Hi! I would also be interested in knowing how to use this functionality. Thanks!!!

**Comment by jasotamame** [comment]
Hey paritoshk, I managed to do it following this 

https://github.com/WestHealth/pyvis/pull/12

**Comment by hadal1337** [comment]
Hey @jasotamame , while it works, the edge titles are disabled, which is not ideal.
