### ISSUE TITLE
BUG: HTML output doesn't display in VSCode Jupyter Notebook

### ISSUE THREAD

**Issue by EricPostMaster** [WestHealth/pyvis#116]
When I run code to display pyvis as HTML in JupyterLab, it works just fine. Unfortunately, when I run the same code in VS Code, it just displays an empty space. I know it is registering that something is there because if I put my cursor there and scroll, the page doesn't move. It must know there is an iFrame there or something, but it doesn't display anything.

Here is what I see in JupyterLab:
![image](https://user-images.githubusercontent.com/58200144/130308591-7528c40b-9c44-42c4-bebf-99effc34df06.png)

Here is what I see in VS Code:
![image](https://user-images.githubusercontent.com/58200144/130308569-9ecd9c98-c0af-4889-b8b0-9b276061257b.png)

⬆️ No output! ⬆️ 😭

Any ideas on what might be wrong?

**Comment by jhunpingco** [comment]
closing as out-of-scope
