### ISSUE TITLE
Visualizing Dynetx

### ISSUE THREAD

**Issue by usbader** [WestHealth/pyvis#120]
Hello all, 

Is there a plan to integrate dynetx? if not, I would like to visualize a dynamic graph with a tool like pyvis. 

https://dynetx.readthedocs.io/en/latest/overview.html

**Comment by jhunpingco** [comment]
no plans for that.

**Comment by laimaretto** [comment]
Hi! ... may be [this](https://github.com/WestHealth/pyvis/issues/59) discussion can give an idea on the matter? They want to know if the network can be displayed as it grows, which in a way is a dynamic representation of the network ...

**Comment by jhunpingco** [comment]
I'm going to close this is *out of scope.*
