### ISSUE TITLE
Very Large Graphs seem to hit radius size limit Physics off.

### ISSUE THREAD

**Issue by john681611** [WestHealth/pyvis#125]
Example with 13.5K nodes
![13.5K node circle](https://user-images.githubusercontent.com/10814889/147227136-fdee46b7-b54f-4a82-acd1-c195d53f4fe2.png)

Where can this be overridden to attempt to be able to see it in its entirety? Amazingly unlike other tools, this was actually very performant with physics turned off.

**Comment by jhunpingco** [comment]
What do you want to override ?

**Comment by john681611** [comment]
The radius limit

**Comment by jakob1379** [comment]
Could you please provide the code snippet for generating the plot?

**Comment by jenghub** [comment]
Running into the same radius issue here, but on a graph of ~6k nodes. Any workarounds?

**Comment by jhunpingco** [comment]
Maybe somebody supporting visjs knows. This is outside the scope of Pyvis.
