### ISSUE TITLE
Styled edges in DOT file don't show up with pyvis but do work with vis network.

### ISSUE THREAD

**Issue by tuschla** [WestHealth/pyvis#128]
I'm having an issue with the styling of my edges in a DOT not being represented when visualizing the graph with pyvis. 
I am just reading the DOT with the `from_DOT` method but the edges with styling `[style="dotted"]` or `[style="dashed"]` have the same appearance as the other (solid) edges. 

Of course I tried adding each edge to the graph with add_edge and then do the styling with something like `dashes=1` for dashed edges and `dashes=[1, 6]` for dotted edges but that's not really the most elegant solution considering the from_DOT method already exists and the edge styling works just fine with my DOT files when I play around with [vis network](https://visjs.github.io/vis-network/examples/network/data/dotLanguage/dotEdgeStyles.html). 

DOT file:
```DOT
digraph {
    a [label=12, entity_id=12, entity_class="truck"];
    b [label=7, entity_id=7,entity_class="bike"];
    c [label=3, entity_id=3, entity_class="car"];
    a -> b[label="solid edge"];                     
    a -> b [label="dashed edge", style=dashed]; 
    a -> c [label="dashed edge", style=dashed]; 
    a -> c [label="dotted edge", style=dotted];      
}
```

This is what I get with pyvis:
![](https://i.ibb.co/G3mRCtj/pyvis.png)

Here is the relevant generated js code:
<details>

```js
    // initialize global variables.
    var edges;
    var nodes;
    var network; 
    var container;
    var options, data;
    
    // This method is responsible for drawing the graph, returns the drawn network
    function drawGraph() {
        var container = document.getElementById('mynetwork');

        var DOTstring = "digraph simple_graph {     a [label=12, entity_id=12, entity_class=\"truck\"];     b [label=7, entity_id=7,entity_class=\"bike\"];     c [label=3, entity_id=3, entity_class=\"car\"];     a -> b[label=\"solid edge\"];                          a -> b [label=\"dashed edge\", style=dashed];      a -> c [label=\"dashed edge\", style=dashed];      a -> c [label=\"dotted edge\", style=dotted];       }";
        var parsedData = vis.network.convertDot(DOTstring);
        
        data = {
          nodes: parsedData.nodes,
          edges: parsedData.edges
        }
        
        var options = parsedData.options;
        options.nodes = {
            shape: "dot"
        }
        
        network = new vis.Network(container, data, options);

        return network;
    }

    drawGraph();
```
</details>

And this is what [vis network](https://visjs.github.io/vis-network/examples/network/data/dotLanguage/dotEdgeStyles.html) draws:
![](https://i.ibb.co/Nt3kK32/vis-network.png)

**Comment by Darkproduct** [comment]
This project uses an very old Version of [vis-network](https://www.npmjs.com/package/vis-network). You can solve this by changing the following lines in the template:
https://github.com/WestHealth/pyvis/blob/b11d105db7059dab1a2c511a740868c54f415bc7/pyvis/templates/template.html#L3-L4
```
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vis-network@latest/styles/vis-network.css" type="text/css" />
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/vis-network@latest/dist/vis-network.min.js"> </script>
```
This will change the `vis-network` version to the latest release. I tested this with the currently latest version `9.1.0`.

Then you also need to change the parsing function of the DOT file here:
https://github.com/WestHealth/pyvis/blob/b11d105db7059dab1a2c511a740868c54f415bc7/pyvis/templates/template.html#L157-L168
```js
var DOTstring = "{{dot_lang|safe}}";
data = vis.network.dotparser.DOTToGraph(DOTstring);

var options = {
    nodes: {
        shape: "dot"
    },
});
{% if options %}
options = Object.assign(options, {{options|safe}})
{% endif %}
```
