### ISSUE TITLE
Network visualisation fails after disabling physics for node or edge.

### ISSUE THREAD

**Issue by mkosturek** [WestHealth/pyvis#13]
After disabling physics for a specific node (by setting argument `physics` in method `Network.add_node()` to `False`) network rendering fails - only background is visible.

Same thing when disabling physics for an edge.

Minimal working example, following tutorial from readme:
```python
from pyvis.network import Network
g = Network()
g.add_node(0, physics=False)
g.add_node(1)
g.add_edge(0,1)
g.show("basic.html")
```
P.S. I love this package!

**Comment by boludo00** [comment]
I see! Good catch, what is happening here is the  `False` that gets interpreted by the JavaScript is a pythonic `False`.  Should be a quick fix.

**Comment by boludo00** [comment]
You can go ahead and update the package and try it out. Latest pyvis 0.1.4.1 should reflect this fix.

**Comment by mkosturek** [comment]
Great! Works like a charm now. Thanks for super-quick response. :)
