### ISSUE TITLE
Publish a new release on PyPi

### ISSUE THREAD

**Issue by szobov** [WestHealth/pyvis#134]
Hi there,

Thanks a lot for the awesome project.
I have a question regarding the releases of this project.
Seems like on PyPI we have the latest version "0.1.9" to be older than the current master branch.
May I ask you to update the package on PyPi, please?
And also the question is can we make a CI in order to update this library more often?
Thanks a lot!

Best regards,
Sergei

**Comment by jhunpingco** [comment]
Updated. Can u check it out?

**Comment by harens** [comment]
Would it be possible to bump the PyPi version to 0.2.1. It's just so I can update the [MacPorts package](https://ports.macports.org/port/py310-pyvis/details/).

Thanks for maintaining this really useful project. 👍 It's helped me out a lot.

**Comment by szobov** [comment]
> Updated. Can u check it out?

Hi @jhunpingco 
Thanks a lot, I see a more recent version on PyPI (0.2.0).
Btw I can help you with setting up a GitHub action to automatically update a version on PyPI, just let me know.

P.S.
I proposed this help because I see that you already made 0.2.1 version on GitHub, but I don't see it on PyPI. :)

Best regards,
Sergei

**Comment by jhunpingco** [comment]
I updated pypi. Let me know how it goes.

**Comment by szobov** [comment]
> I updated pypi. Let me know how it goes.

Yes, thanks, it works for me.
I'll close this issue since it's solved, but please let me know if you change your mind about the automatic update of the new version on PyPI.

All the best,
Sergei
