### ISSUE TITLE
Network().add_node() method does not parse **options dict. 

### ISSUE THREAD

**Issue by cmartia** [WestHealth/pyvis#142]
I have tried using keyword arguments described in https://visjs.github.io/vis-network/docs/network/nodes.html# through the pyvis wrapper (eg. imagePadding=XX) but it has no effect on the output html.

**Comment by jhunpingco** [comment]
I updated version on pypi. Try it out and let me know if u still have this problem.

**Comment by jhunpingco** [comment]
closing.
