### ISSUE TITLE
Custom sliders?

### ISSUE THREAD

**Issue by KrishivVora** [WestHealth/pyvis#156]
I was wondering if there was a way to have custom sliders similar to the various buttons/sliders in the network options? Say I want to set a slider for a variable 'time' and as I drag the slider, elements on the network visualization change as defined in some function that I input, but dynamically. Currently I can do this with ipywidgets but it isn't dynamic so the .html has to be re-made each time the slider is adjusted. This is not smooth and results in the positions of the nodes changing constantly since they seem to be randomly placed each time the graph is redrawn.

**Comment by jhunpingco** [comment]
There is no straightforward way to do this with the current documentation because a new HTML document has to be created for every slider position.
