### ISSUE TITLE
pyvis offline mode

### ISSUE THREAD

**Issue by ChrisDelClea** [WestHealth/pyvis#159]
Hey guys, thanks for this nice wrapper of visjs. 
Could you please offer a version where the dependencies to CDN are inluded dirctly 
so also people without internet can use the package? 

Best regards
Chris

**Comment by jhunpingco** [comment]
There is an issue with the vis.js license regarding distributing it. You'll have to download and reference visjs manually yourself.

**Comment by JohnOmernik** [comment]
Could it be setup where we specify the location and download it manually? but essentially operates in offline mode?
