### ISSUE TITLE
Does this module do any computation, or does it only create a HTML file?

### ISSUE THREAD

**Issue by markstuttword** [WestHealth/pyvis#169]
I have a network with a lot of nodes and I'm trying to pre-compute the nodes position such that it does not have to be run entirely in the browser every time that the page is opened.
I'm wondering if this module does any computation at all. It looks like it's only a Python wrapper that produces an HTML output for vis.js.

**Comment by jhunpingco** [comment]
That's basically right. The positions are calculated by vis.js.
