### ISSUE TITLE
could not render html, saying cdn recourses problem 

### ISSUE THREAD

**Issue by cosmopoli12** [WestHealth/pyvis#178]
Dear all,

Thanks for your great work, there is rendering issue as follows.

nt.show_buttons(filter_=['physics']) 
nt.show("network.html")
display(HTML('network.html'))

* Local cdn resources have problems on chrome/safari when used in jupyter-notebook. 

 the error came up both in Jupyter lab and Google colab!

Please kindly help check!

**Comment by cosmopoli12** [comment]
and the title printed out two times. 

kiitos!

**Comment by js-konda** [comment]
Hi 

while using notebook in chrome browser, to render the graph, pass additional kwarg ‘cdn_resources’ as ‘remote’ or ‘inline’

reference: https://pyvis.readthedocs.io/en/latest/tutorial.html

**Comment by cosmopoli12** [comment]
great help thanks!
