### ISSUE TITLE
drawing wrong arrow directions

### ISSUE THREAD

**Issue by cdanielmachado** [WestHealth/pyvis#18]
Dear developers, thank you for this great library. 

Unfortunately, it seems there are some issues with directed graphs, here is the first one.

When drawing directed graphs the arrows are plotted in the wrong direction:

![screenshot 2018-12-06 at 10 12 39 2](https://user-images.githubusercontent.com/2588245/49574244-3a87c680-f940-11e8-83c0-f22758557ea4.png)

**Comment by boludo00** [comment]
Looks like I mixed up my `from` and `to` definitions in an Edge. Fixing this now :)
