### ISSUE TITLE
Demo example (GoT characters) is not reproducible anymore due to data being moved.

### ISSUE THREAD

**Issue by therhappy** [WestHealth/pyvis#182]
Hello,

The tutorial which is the main chunk of documentation presents the GoT example as one of the examples with most functionalities: use of the adjacency list, HTML in "title" value, highlights, custom.

However this example cannot be reproduced anymore due to the supporting data now being unavailable: https://mathbeveridge.github.io/data/stormofswords.csv no longer exists as Andrew stopped hosting data on their page.

The demo should be updated to redirect users to https://github.com/WestHealth/pyvis/blob/master/notebooks/NetworkOfThrones.csv which is conveniently hosted in this repo.

Thanks!

**Comment by js-konda** [comment]
Hi thank you for bringing this up. We have fixed the issue.
