### ISSUE TITLE
issue with write_html

### ISSUE THREAD

**Issue by sudesh0sudesh** [WestHealth/pyvis#189]
I am not sure why the specific code below is added in newer version it opens a new tab, eventhough, I just want to write to html

                webbrowser.open(f"{tempdir}/{name}")

**Comment by JohnOmernik** [comment]
Agreed.  We should have a flag that allows us to not issue the webbrowser.open. 

Another thought, when .show is called, could we provide a directory rather than ./{html_name} I want it to write to the local directory, but the . passed to the browser (when I want it to show) doesn't work.

**Comment by norweeg** [comment]
this issue should be closed.  this is already implemented
