### ISSUE TITLE
unable to draw bidirectional dependencies

### ISSUE THREAD

**Issue by cdanielmachado** [WestHealth/pyvis#19]
I would like to plot this, which is a very common pattern in my networks:

![bidirectional png 001](https://user-images.githubusercontent.com/2588245/49574703-4aec7100-f941-11e8-89d5-4f7965c9573f.png)

Unfortunately, it doesn't seem to work:

![screenshot 2018-12-06 at 10 13 32 2](https://user-images.githubusercontent.com/2588245/49574728-563f9c80-f941-11e8-96e7-ed401ad6bebf.png)

Is this a bug or a limitation of the network structure?

**Comment by boludo00** [comment]
Yes this is a bug I found thanks to your feedback. This is an easy fix ill post the results in a sec.

**Comment by boludo00** [comment]
This is what it looks like after the fix. I know it doesnt have the two edges visually, but instead is interpreted as one line with the two arrows. So this just has to be the way that VisJS draws bidirectional edges.

![image](https://user-images.githubusercontent.com/8398241/49603511-53907780-f940-11e8-8155-9b15f00e0b08.png)

**Comment by boludo00** [comment]
![image](https://user-images.githubusercontent.com/8398241/49611190-a6285e80-f955-11e8-8f18-110342520bef.png)
If you set an edge smooth type, this enables the edge smoothing in the backend which has those results :)

**Comment by cdanielmachado** [comment]
This is amazing, exactly what I needed, thanks!
