### ISSUE TITLE
The `set_options()` method of the pyvis.network.Network class is causing an error

### ISSUE THREAD

**Issue by chiboreache** [WestHealth/pyvis#210]
# Bug Report

## Summary
The `set_options()` method of the `pyvis.network.Network` class is causing an error when trying to call the `replace()` method on a dictionary object.

## Steps to reproduce
1. Import the `pyvis.network` module
2. Create an instance of the `pyvis.network.Network` class
3. Define a dictionary of options
4. Call the `set_options()` method on the `Network` instance, passing in the options dictionary

## Expected behavior
The options should be applied to the network visualization and no error should occur.

## Actual behavior
An error occurs, with the following message:

```sh
Traceback (most recent call last):
File "/path/to/file.py", line 82, in <module>
nt.set_options(options)
File "/path/to/pyvis/network.py", line 1008, in set_options
self.options = self.options.set(options)
File "/path/to/pyvis/options.py", line 221, in set
options = new_options.replace("\n", "").replace(" ", "")
attributeError: 'dict' object has no attribute 'replace'
```

## Environment
- Python version: 3.10
- pyvis version: 0.3.1
- Operating System: Arch Linux

## Additional information

```python
    nt = Network('800px', '100%')

    options = {
        "physics": {
            "repulsion": {"strength": 5000},
            "hierarchicalRepulsion": {"nodeDistance": 200}
        }
    }

    #options = json.dumps(options).replace("\n", "").replace(" ", "")  # not helped

    nt.set_options(options)

    nt.from_nx(G)
    nt.toggle_physics(True)
    nt.show('nx.html')
```

**Comment by karunpoudel** [comment]
`Options.set(new_options)` assumes new_options is json string which is not intuitive, dict would have made more sense here.
Also, in 0.3.2, Options.set() function doesn't set any instance variable, it just returns dict of new_options; am I missing anything?
