### ISSUE TITLE
Recommend any html viewer?

### ISSUE THREAD

**Issue by talhaanwarch** [WestHealth/pyvis#23]
would you please like to recommend me any html viewer that can visualize heavy graph. btw thanks for such a great library

**Comment by boludo00** [comment]
If you look at this [performance test](http://visjs.org/examples/network/exampleApplications/worldCupPerformance.html) you will see the way VisJS handles visualizing a heavy graph. The way you choose to draw the edges has a big affect on performance. Looking at that example you will see that the nodes take a good while to stabilize. But if you hold down the click and drag around any part of the canvas you will see the edges become hidden and the nodes stabilize more freely.
If you are having trouble with performance I would recommend first trying to set the edge type to something other than the default which takes the most time. 

Example:
```python
g = Network()
g.set_edge_smooth("discrete")
# add a bunch of nodes

g.show("blah.html")
```

**Comment by boludo00** [comment]
I will close this for now
