### ISSUE TITLE
Pyvis HTML Output does not use 100% of the page

### ISSUE THREAD

**Issue by vkuehn** [WestHealth/pyvis#269]
This peace of code works nicely but in the outputfile only 30% of the window are used (either Chome or Firefox)

`import networkx as nx
from pyvis.network import Network

G = nx.Graph()
G.add_node(1)
G.add_node(2)
G.add_node(3)

G.add_edge(1, 2)
G.add_edge(1, 3)

net = Network(height="100%", width="100%", directed=True, notebook=True)
net.from_nx(G)
net.show("simple.html")
`

**Comment by vkuehn** [comment]
the reason is that the height is actually the height of the drawn network, which is usually not shown as 100%, not sure when and where such a configuration is needed but actually I would prefere a window hight and with especially when embedding it.

so Feature change request ?

**Comment by vkuehn** [comment]
closed because of inactivity

**Comment by fernandocfbf** [comment]
Quite late, but I just faced the same issue when displaying a Pyvis network. The output only occupied about a quarter of my screen's height. To fix this, I modified the height parameter to "100vh" instead of "100%". Your code would look like this:

```
net = Network(height="100vh", width="100%", directed=True, notebook=True)
net.from_nx(G)
net.show("simple.html")
```
