### ISSUE TITLE
Creating "group" for nodes

### ISSUE THREAD

**Issue by urschni** [WestHealth/pyvis#29]
Vis.js gives to option to create groups to apply layout and style options. How would I do this with pyvis? Could you please give a simple example.

**Comment by boludo00** [comment]
Hi, you can just use the "group" keyword arg when adding nodes.
```python
from pyvis.network import Network

g = Network()
g.add_node(0, group=0)
g.add_node(1, group=0)
g.add_node(2, group=1)
g.add_node(3, group=1)
g.add_node(4, group=2)
g.add_node(5, group=2)
g.show("groups.html")
```
Result:
![image](https://user-images.githubusercontent.com/8398241/60826237-4485d800-a162-11e9-8ba2-32ed95be9cab.png)

**Comment by kk-hiraskar** [comment]
How to show legend for the colors ?  
[or]  
how to get what color is applied to group number?


_Because without legend interpretation, difficult to represent the graph_

**Comment by mtfang** [comment]
@kk-hiraskar I felt your pain today, but found the solution. Better late than never...

The solution is to use the underlying visJS library. You can find an example called "Custom Groups" in the [visJS examples library](https://visjs.github.io/vis-network/examples/). Pass through your group parameters via `network.Network.set_options()` where taking their example you'd have something like:
```
nt = Network()
nt.set_options("""
const options = {
groups: {
    diamonds: {
      color: { background: "red", border: "white" },
      shape: "diamond",
    },
    dotsWithLabel: {
      label: "I'm a dot!",
      shape: "dot",
      color: "cyan",
    },
    mints: { color: "rgb(0,255,140)" },
    icons: {
      shape: "icon",
      icon: {
        face: "FontAwesome",
        code: "\uf0c0",
        size: 50,
        color: "orange",
      }
    }
}
""")
```
