### ISSUE TITLE
Allow setting options as dictionary

### ISSUE THREAD

**Issue by Haigutus** [WestHealth/pyvis#30]
With using .show_buttons() it is possible to test all configuration directly in browser and then copy the settings as a json, but it is not possible to use it as a input in python.

My dirty solution works like this ->

1. changed this line in source code

 ```
 def get_network_data(self):
        return (self.nodes, self.edges, self.height,
                self.width, json.dumps(self.options))
```
2. Copied JSON from the UI after setting desirable options (manually set all true and false options to python True and False)

options = {
  "nodes": {
    "shape": "dot",
    "size": 10
  },
  "edges": {
    "color": {
      "inherit": True
    },
    "smooth": False
  },
  "layout": {
    "hierarchical": {
      "enabled": True,
      "direction": "LR",
      "sortMethod": "directed"
    }
  },
  "interaction": {
    "navigationButtons": True
  },
  "physics": {
    "hierarchicalRepulsion": {
      "centralGravity": 0,
      "springLength": 75,
      "nodeDistance": 145,
      "damping": 0.2
    },
    "maxVelocity": 28,
    "minVelocity": 0.75,
    "solver": "hierarchicalRepulsion"
  }
}

3. Result

graph.options = options

graph.show(r"test.html")

![image](https://user-images.githubusercontent.com/11408965/55438038-30ea3480-55a9-11e9-8ca7-eb26edbf51d7.png)

**Comment by boludo00** [comment]
I'll work on a solution for this. Process would still have those 2 layers (generate options in browser first, go back to code and copy paste options into some method that processes it and overrides default options)

**Comment by boludo00** [comment]
The following is now possible:

```python
from pyvis.network import Network

g = Network()

g.add_node(0, group=0)
g.add_node(1, group=0)
g.add_node(2, group=1)
g.add_node(3, group=1)
g.add_node(4, group=2)
g.add_node(5, group=2)
g.add_edges([(0, 1), (2,1), (3,4), (3,2), (4,5), (1,4), (1,5)])

g.set_options("""
var options = {
  "nodes": {
    "borderWidth": 0,
    "borderWidthSelected": 7,
    "fixed": {
      "x": true,
      "y": true
    },
    "font": {
      "size": 13,
      "strokeWidth": 18,
      "strokeColor": "rgba(165,215,255,1)"
    },
    "shape": "dot"
  },
  "edges": {
    "color": {
      "inherit": true
    },
    "scaling": {
      "label": {
        "drawThreshold": 16
      }
    },
    "smooth": {
      "forceDirection": "none"
    }
  },
  "interaction": {
    "hideEdgesOnDrag": true
  },
  "physics": {
    "minVelocity": 0.75
  }
}
""")
```

This will override the options default behavior of their internal objects (like layout, interaction, configure) and just replace it with a JSON decoded string. 
Again, process would be:
- use `show_buttons` method to generate playground to tweak options yourself
- copy generated options
- paste these options into `network.set_options` call (copy entire output from generated options)
   -- USE TRIPLE QUOTES
- run script with `set_options` call

It may seem awkward to have to run your same script a total of 2 times to get your final output, but this feature is there for those who want to have an environment to play with the data in a live setting, allowing you to see the effects of each option in real time. Once you are happy with your output you can just save the options as a string and use that to override the network's options.

**Comment by Haigutus** [comment]
Nice, this is perfect.

**Comment by soerendip** [comment]
Here it creates an empty graph. Do I have to not call `.show_buttons()` the second time??

**Comment by houtanb** [comment]
Does this support all `vis.js` options? 

`show_buttons` does not show the `widthConstraint` option for `nodes` discussed on this page https://visjs.github.io/vis-network/docs/network/nodes.html and so I tried to set it via:
```
g.set_options("""
var options = {
  "nodes": {
    "widthConstraint": {
      "minimum": 0.5,
      "maximum": 1
    },
    ...
```
but did not get the expected results....
