### ISSUE TITLE
Example notebook

### ISSUE THREAD

**Issue by psychemedia** [WestHealth/pyvis#31]
It would be useful to add an example notebook that could be run in MyBinder for example.

Example notebook based on docs attached.

The repo also runs straightforwardly in MyBinder: adding a MyBinder button to the README would simplify access to this: [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/WestHealth/pyvis/master)

[Example.ipynb.zip](https://github.com/WestHealth/pyvis/files/3069622/Example.ipynb.zip)

**Comment by boludo00** [comment]
Good suggestion. Got a basic working example running now.
