### ISSUE TITLE
requirement conflict in setup.py and requirements.txt

### ISSUE THREAD

**Issue by pebbie** [WestHealth/pyvis#32]
in setup.py the dependency for ipython is ==5.3.0 but in requirements.txt it's written >=5.3.0
therefore installation of pyvis using pip will downgrade back the existing ipython to 5.3.0. please fix and update python wheel file

**Comment by boludo00** [comment]
Solved by #33

**Comment by jamieforth** [comment]
Would it also be possible to upload a new package with this fix to Pypi please?
