### ISSUE TITLE
edge labels

### ISSUE THREAD

**Issue by eannam** [WestHealth/pyvis#39]
Hi, is it possible to display edge labels/attributes with pyvis? Thanks.

**Comment by boludo00** [comment]
You can supply a call to `add_edge` with the `title` kwarg to display a tooltip over edges when you hover over them.

Example:

```python
from pyvis.network import Network

g = Network()
g.add_node(0)
g.add_node(1)
g.add_edge(0, 1, title="this is an edge label")
```

**Comment by ybaktir** [comment]
It should should "label" not "title", like this:
```python
from pyvis.network import Network

g = Network()
g.add_node(0)
g.add_node(1)
g.add_edge(0, 1, label="this is an edge label")

```
