### ISSUE TITLE
Network.from_nx doesnt import isolated nodes if edges exist 

### ISSUE THREAD

**Issue by jmtaysom** [WestHealth/pyvis#60]
When edges exist the only nodes that are created are ones that are part of edges. Any nodes not part of an edge dont get imported.  `nx.isolates(G)` will return an iterable that has all the nodes that are not part of edges. Looping over this would allow for adding these nodes after adding the nodes from the edges.

**Comment by nocluebutalotofit** [comment]
This issue can be closed, now.
