### ISSUE TITLE
to_json error

### ISSUE THREAD

**Issue by yazoo178** [WestHealth/pyvis#64]
Hello

Getting an error when calling the to_json method.

~/anaconda3/envs/default/lib/python3.6/site-packages/pyvis/network.py in <lambda>(o)
    767 
    768     def to_json(self):
--> 769         return json.dumps(self, default=lambda o: o.__dict__,
    770                           sort_keys=True, indent=4)
    771 

AttributeError: 'builtin_function_or_method' object has no attribute '__dict__'

Any suggestions?

**Comment by boludo00** [comment]
Hey @yazoo178 ,
I have changed default to_json to utilize the `jsonpickle` module. So below is a snippet that works for me:

```python
g = Network(notebook=True)
g.add_nodes([0,2,3,5])
g.to_json()
```
![image](https://user-images.githubusercontent.com/8398241/86044146-902e3300-b9fe-11ea-9425-d3b697e68d3f.png)
