### ISSUE TITLE
None showed when heading is not provided

### ISSUE THREAD

**Issue by GalenWong** [WestHealth/pyvis#69]
![image](https://user-images.githubusercontent.com/33505320/89489015-1008a380-d7dc-11ea-9aca-c25967e7f90e.png)

As shown in the image, the rendered HTML shows `None` for heading. This is caused by PR #67. The logic of HTML rendering template should not display the `h2` tag if the `heading` is `None`. 

@WilsonHChung would you mind looking into that? I like the heading features a lot BTW.

**Comment by andrewlaikh** [comment]
Hi, I have this issue too and figured out that you could just change the heading to heading = '' to stop it showing.

**Comment by GalenWong** [comment]
@andrewlaikh Yes indeed that would be a work around. However, this breaks existing apps that is not aware of the new `heading` parameter and the `None` would show up for no reason. We want to ideally avoid this unexpected change in behavior.
