### ISSUE TITLE
setting edge color?

### ISSUE THREAD

**Issue by fanzheng10** [WestHealth/pyvis#72]
Hi, I am trying to find a way to set edge color without luck. Can anyone help me, or let me know if it is going to be implemented in near future?

I tried `show_buttons` function, it gave me a toggle to set colors but didn't seem to be effective.
![image](https://user-images.githubusercontent.com/22034405/92432919-7290ee80-f150-11ea-8923-3662763e26c5.png)

Thanks.

**Comment by boludo00** [comment]
Hi, it seems this UI VisJS feature is broken at the moment. You can still pass an edge color like:

`G.add_edge(1, 2, color="red")`
