### ISSUE TITLE
feature request: edge label

### ISSUE THREAD

**Issue by jeromegit** [WestHealth/pyvis#86]
Hi, great Python library!
I was wondering if it would be possible to add a label to edges the same there's one for nodes.

Thanks!

**Comment by laimaretto** [comment]
Hi @jeromegit , yes, you can add label to edges.

After you've created the network object `G`, and identified a pair of nodes, you can add a label to the edge as follows:

`G.add_edge(source=node_A, to=node_B, label=edgeLabel)`

In this case, `edgeLabel` is a string that will be shown over the edge between nodes `A` and `B`.

**Comment by jeromegit** [comment]
Thanks @laimaretto !
I didn't see it in the doc (https://pyvis.readthedocs.io/en/latest/documentation.html?highlight=add_edge#pyvis.network.Network.add_edge) and so I assume it wasn't possible.
A quick look at the method definition doesn't show it either but it's probably hidden somewhere.

I'll try it later.

Thanks again!

**Comment by mixartemev** [comment]
I extremely need this feature too.
`label` attr in `add_edge` isn't working (in docs it is absent also).

**Comment by Linnore** [comment]
Any update on this issue? Displaying edge weights or edge labels are extremely useful. It's a pity not able to add this feature.
