### ISSUE TITLE
Looking for Ways to Stop Physics

### ISSUE THREAD

**Issue by thiaraortiz** [WestHealth/pyvis#88]
Hi!

I’m currently building a network with a large number of nodes and edges. I am wanting to first render the network with physics enabled so that they’re all positioned. Once the graph has stabilized, I’d like to go ahead and disable physics to prevent nodes from flying around.

I’ve tried using the improvedLayout options along with directly disabling physics and enabling stabilization; however, in both cases the network is jumbled up in a circle. 

I’ve read up on some of the documentation from Vis.Js which eludes to StabilizationEvents which can be used to call back and disable physics; however, I’m not really sure how to go about this with Pyvis. 

Any suggestions would really help, I’ve been digging through the documentation for the past few hours.

**Comment by boludo00** [comment]
Hey there, did you find a solution? 
All I can think of right now is to use the UI options to manually disable physics after stabilization.
You can enable the UI with 
```python
g = Network()
g.from_nx(nx.cycle_graph(10))
g.show_buttons(filter_=["physics"])
```

and you should get something like:
![image](https://user-images.githubusercontent.com/8398241/116588092-fa8a5b00-a8cf-11eb-98ff-3a19e622280a.png)

Not sure if that's what you're looking for, but its a start.

**Comment by thiaraortiz** [comment]
Unfortunately, I did not find an adequate solution-- I'd like to avoid having a user select the disable physics button.

I read through the code for Pyvis on github but I wasn't able to figure out how to get this to work programmatically.

**Comment by boludo00** [comment]
Yeah unfortunately once the visualization has rendered and stabilized, that's out of pyvis' control. There's probably a way to determine if the network has loaded and then disable the physics vis the JavaScript though... If this is possible then the template can be modified to enable that change.

**Comment by lastsudo** [comment]
hi, just add `g.toggle_physics(False)` before you show as html file

`g = Network()
g.from_nx(nx.cycle_graph(10))
g.toggle_physics(False)`

**Comment by g-ioannou** [comment]
A way I found to improve the loading performance is to disable physics (+0 avoid overlap,+low spring force) and group nodes into communities,with each same-community nodes having the same initial position (you can set a random position for each community). A graph  with  ~1300 nodes and ~13.000 edges loaded significantly faster with this method. 

When you start the visualization you will notice that only a number of nodes corresponding to the community number will appear. Just drag a single node , the graph will expand and you will see all the nodes.

**Comment by kk-hiraskar** [comment]
> hi, just add `g.toggle_physics(False)` before you show as html file
> 
> `g = Network()` `g.from_nx(nx.cycle_graph(10))` `g.toggle_physics(False)`

** If physics is disabled before showing HTML, then everything will just be shown in a circle without proper positioning!!
cannot do like this :-(

![image](https://user-images.githubusercontent.com/19647561/160530272-b553496a-1f7f-4f07-9a05-0dfcb872494f.png)

**Comment by grahamharrison68** [comment]
If you launch the network in a separate browser window you can untick physics, then generate and capture the options and then feed them directly into the set up which will neatly launch the next network with the physics disabled but it still seems to generate a decent layout for my network. Here is the source code ...

options = r'var options = {"edges": {"color": {"inherit": true},"smooth": false},"physics": {"enabled": false,"minVelocity": 0.75}}'
net.set_options(options)

**Comment by rtackx** [comment]
Here is a workaround, modify templates/template.html:
```
network.once("stabilizationIterationsDone", function() {
  document.getElementById('text').innerHTML = '100%';
  document.getElementById('bar').style.width = '496px';
  document.getElementById('loadingBar').style.opacity = 0;
  // really clean the dom element
  setTimeout(function () {document.getElementById('loadingBar').style.display = 'none';}, 500);
  // add this line
  network.setOptions( { physics: false } );
});
```
It stops the physics after the layout is loaded.

**Comment by rorysmith85** [comment]
> Here is a workaround, modify templates/template.html:
> 
> ```
> network.once("stabilizationIterationsDone", function() {
>   document.getElementById('text').innerHTML = '100%';
>   document.getElementById('bar').style.width = '496px';
>   document.getElementById('loadingBar').style.opacity = 0;
>   // really clean the dom element
>   setTimeout(function () {document.getElementById('loadingBar').style.display = 'none';}, 500);
>   // add this line
>   network.setOptions( { physics: false } );
> });
> ```
> 
> It stops the physics after the layout is loaded.

Could you provide a few more details on how to implement that? I am trying to render in streamlit and it is taking forever to load. And then is very slow upon rendering. Thanks.

**Comment by RGPrime235** [comment]
> I'm not sure about streamlit, and I don't know if this will help you, but here's a function that implants rtackx's code in the HTML file via Python automatically (it helped me...opens up with nice layout and no physics):

from pyvis.network import Network
import re
import os
import webbrowser


def build_html(pyvis_network, html_filepath):    
    # Load the current HTML file and stringify it
    html = pyvis_network.generate_html(html_filepath)
    
    # Define the pattern using regex to match the script tags and their contents...in the HTML file, the regex contents (.*?) should return everything up to and including the function call for 'drawGraph()' near the bottom of the file.
    pattern = r'(.*?)<\/script>\n    <\/body>'
    
    # Define the 'physics' modification which will be placed after 'drawGraph()' in the HTML file, which will turn off the physics after the layout is loaded.
    physics_mod = """ 
                    network.once("stabilizationIterationsDone", function() {
                    document.getElementById('text').innerHTML = '100%';
                    document.getElementById('bar').style.width = '496px';
                    document.getElementById('loadingBar').style.opacity = 0;
                    // really clean the dom element
                    setTimeout(function () {document.getElementById('loadingBar').style.display = 'none';}, 500);
                    // add this line
                    network.setOptions( { physics: false } );
                    });
                """

    # Make f-string to consist of the HTML/JS from the beginning up to 'drawGraph()' with re.findall(pattern, html, re.DOTALL)[0], followed by the physics mod which will run after the layout has been loaded, and finally, add closing </script>, </body>, and </html> tags
    html_content = f'{re.findall(pattern, html, re.DOTALL)[0]}{physics_mod}</script>\n    </body>\n</html>'

    return html_content


if __name__ == '__main__':
    # Your network
    nt = Network()

    # Make initial HTML file with nt.show()
    html_file = "test.html"
    nt.show(html_file)

    # Perform 'surgery' on HTML file by calling 'build_html' and adding in physics mod
    new_html = build_html(nt, html_file)

    # Save the HTML content to a file
    with open(f'{html_file}', 'w') as f:
        f.write(new_html)

    file_path = <full path to your new html file...for some reason I can't get it to work by putting the relative path>

    # Open in web browser, but not necessary
    webbrowser.open_new_tab('file://' + file_path)

**Comment by RGPrime235** [comment]
> 

> I'm not sure about streamlit, and I don't know if this will help you, but here's a function that implants rtackx's code in the HTML file via Python automatically (it helped me...opens up with nice layout and no physics):

from pyvis.network import Network
import re
import os
import webbrowser


def build_html(pyvis_network, html_filepath):    
    # Load the current HTML file and stringify it
    html = pyvis_network.generate_html(html_filepath)
    
    # Define the pattern using regex to match the script tags and their contents...in the HTML file, the regex contents (.*?) should return everything up to and including the function call for 'drawGraph()' near the bottom of the file.
    pattern = r'(.*?)<\/script>\n    <\/body>'
    
    # Define the 'physics' modification which will be placed after 'drawGraph()' in the HTML file, which will turn off the physics after the layout is loaded.
    physics_mod = """ 
                    network.once("stabilizationIterationsDone", function() {
                    document.getElementById('text').innerHTML = '100%';
                    document.getElementById('bar').style.width = '496px';
                    document.getElementById('loadingBar').style.opacity = 0;
                    // really clean the dom element
                    setTimeout(function () {document.getElementById('loadingBar').style.display = 'none';}, 500);
                    // add this line
                    network.setOptions( { physics: false } );
                    });
                """

    # Make f-string to consist of the HTML/JS from the beginning up to 'drawGraph()' with re.findall(pattern, html, re.DOTALL)[0], followed by the physics mod which will run after the layout has been loaded, and finally, add closing </script>, </body>, and </html> tags
    html_content = f'{re.findall(pattern, html, re.DOTALL)[0]}{physics_mod}</script>\n    </body>\n</html>'

    return html_content


if __name__ == '__main__':
    # Your network
    nt = Network()

    # Make initial HTML file with nt.show()
    html_file = "test.html"
    nt.show(html_file)

    # Perform 'surgery' on HTML file by calling 'build_html' and adding in physics mod
    new_html = build_html(nt, html_file)

    # Save the HTML content to a file
    with open(f'{html_file}', 'w') as f:
        f.write(new_html)

    file_path = <full path to your new html file...for some reason I can't get it to work by putting the relative path>

    # Open in web browser, but not necessary
    webbrowser.open_new_tab('file://' + file_path)

**Comment by rtackx** [comment]
1) Open templates/template.html of pyvis usually located in the user library folder (~/.local/lib or wherever it is installed)
2) Modify this file accordingly like shown above (one line to add)

This hack just adds a parameter in a JavaScript object to shut down the physics of the layout right after the loading finishes.

**Comment by mb-hz** [comment]
This is the best answer so for, if you want the network stay still. Would be really game changing if we can control this on hot.

**Comment by tsp-kucbd** [comment]
> Here is a workaround, modify templates/template.html:
> 
> ```
> network.once("stabilizationIterationsDone", function() {
>   document.getElementById('text').innerHTML = '100%';
>   document.getElementById('bar').style.width = '496px';
>   document.getElementById('loadingBar').style.opacity = 0;
>   // really clean the dom element
>   setTimeout(function () {document.getElementById('loadingBar').style.display = 'none';}, 500);
>   // add this line
>   network.setOptions( { physics: false } );
> });
> ```
> 
> It stops the physics after the layout is loaded.

The best solution I have found so far is to create my own template directory, copy template.html into it, add the line suggested by @rtackx and then use _set_template_dir_ to that location.

Here two graph files are generated, one with physics still working (_net_moving.html_) and one where the physics was turned off after loading (_net_notmoving.html_)
```
from pyvis.network import Network
import numpy as np

N = 300
net = Network(notebook=False)
net.add_nodes(np.arange(0,N), value=[1]*N)
[net.add_edge(i, i+1) for i in range(N-1)]

net.force_atlas_2based()
net.show("net_moving.html", notebook=False)

# give the path to your template directory which contains the changed template.html
template_dir = './mytemplates'
net.set_template_dir(template_dir)
net.show("net_notmoving.html", notebook=False)

```

**Comment by bruebakerr** [comment]
> > Here is a workaround, modify templates/template.html:
> > ```
> > network.once("stabilizationIterationsDone", function() {
> >   document.getElementById('text').innerHTML = '100%';
> >   document.getElementById('bar').style.width = '496px';
> >   document.getElementById('loadingBar').style.opacity = 0;
> >   // really clean the dom element
> >   setTimeout(function () {document.getElementById('loadingBar').style.display = 'none';}, 500);
> >   // add this line
> >   network.setOptions( { physics: false } );
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It stops the physics after the layout is loaded.
> 
> The best solution I have found so far is to create my own template directory, copy template.html into it, add the line suggested by @rtackx and then use _set_template_dir_ to that location.
> 
> Here two graph files are generated, one with physics still working (_net_moving.html_) and one where the physics was turned off after loading (_net_notmoving.html_)
> 
> ```
> from pyvis.network import Network
> import numpy as np
> 
> N = 300
> net = Network(notebook=False)
> net.add_nodes(np.arange(0,N), value=[1]*N)
> [net.add_edge(i, i+1) for i in range(N-1)]
> 
> net.force_atlas_2based()
> net.show("net_moving.html", notebook=False)
> 
> # give the path to your template directory which contains the changed template.html
> template_dir = './mytemplates'
> net.set_template_dir(template_dir)
> net.show("net_notmoving.html", notebook=False)
> ```

To build upon the excellent solutions that @rtackx and @tsp-kucbd provided, I update my _custom_ template with the following `else` block at the end of the file.  This additional will successfully allow the physics to also halt for smaller visualizations (the block at the end of the template _as-is_ would only affect visualizations greater than 100 nodes).

```html
          network.once("stabilizationIterationsDone", function() {
              document.getElementById('text').innerHTML = '100%';
              document.getElementById('bar').style.width = '496px';
              document.getElementById('loadingBar').style.opacity = 0;
              // really clean the dom element
              setTimeout(function () {document.getElementById('loadingBar').style.display = 'none';}, 500);
              // add this line
              network.setOptions( { physics: false } );
          });
        
         // start block addition
         {% else %}
              network.on("stabilizationIterationsDone", function() {
                  network.setOptions( { physics: false } );
              });
        //end block addition
{% endif %}
``` 

This template is then leveraged/called via following line of code

```python
net.set_template_dir('./mytemplates',template_file='nmtemplate.html')
```
