### ISSUE TITLE
Hide Edges' arrowheads

### ISSUE THREAD

**Issue by Melzonko** [WestHealth/pyvis#99]
Hi, I there a way to hide the Edges' arrowheads from a directed graph?  i.e. Having Edges without arrows in the below example:

from pyvis.network import Network
import networkx as nx
g = nx.MultiGraph()
g.add_node(0)
g.add_node(1)
g.add_edge(0, 1)
g.add_edge(0, 1)
nt = Network(directed=True)
nt.from_nx(g)
nt.set_edge_smooth('dynamic')
nt.show('foo.html')

![image](https://user-images.githubusercontent.com/17943997/122273720-cf48e300-cef2-11eb-81b2-165352f25d3e.png)

**Comment by laimaretto** [comment]
I'm doing this. You'll have to set options to the graphs with the following:

```
"edges": {
    "arrowStrikethrough": false,
    "color": {
    "inherit": false
    },
    "font": {
    "size": 10,
    "align": "top"
    },
    "smooth": false
},
```

This should hide the arrows of the edges.

**Comment by Melzonko** [comment]
@laimaretto  Thank you for the prompt answer. I actually tried your workaround but unfortunately, it didn't give me the desired result. Please check the code in below:

from pyvis.network import Network
import networkx as nx
g = nx.MultiGraph()
g.add_node(0)
g.add_node(1)
g.add_edge(0, 1)
g.add_edge(0, 1)
nt = Network(directed=True)
nt.from_nx(g)
nt.set_edge_smooth('dynamic')

nt.set_options('''
var options = {
"edges": {
    "arrowStrikethrough": false,
    "color": {
    "inherit": false
    },
    "font": {
    "size": 10,
    "align": "top"
    },
    "smooth": false
    }
}
''')
nt.show('foo.html')


**Output>>** 

![image](https://user-images.githubusercontent.com/17943997/122386178-ab32e380-cf7e-11eb-8d19-e8a5a17ff2d6.png)


What I'm looking for is the same as in the below depiction (Edges with no heads):

![image](https://user-images.githubusercontent.com/17943997/122386828-50e65280-cf7f-11eb-9367-c529d2049020.png)

**Comment by laimaretto** [comment]
Hi @Melzonko , yes I understand perfectly what you want (because that is what I'm doing). 

In addition to what you've shared, let me mention that when I create my topologies, I also create the `nt` object but without the `directed` parameter (which, I guess, is forcing you the arrows). Since you don't want the arrows at all, may be you can try out without that parameter.

Another difference, I'm adding nodes and edges to the object itself and not importing that from `neworkx` as you are performing. Hopefully removing the `directed` parameter should do it ...

This is what I have ...
```
G = Network("800px", "1300px", heading="")

G.set_options("""
    var options = {

        "edges": {
            "arrowStrikethrough": false,
            "color": {
            "inherit": false
            },
            "font": {
            "size": 10,
            "align": "top"
            },
            "smooth": false
        },

    }
    """)
```

And this is what I can produce ...

![image](https://user-images.githubusercontent.com/8891825/122395444-5d51b780-cf4d-11eb-8fe4-7e9a158ba8c5.png)

**Comment by Melzonko** [comment]
@laimaretto  You're right regarding the 'directed=True' as it forces the arrows to be created, but did you try to create Two Edges between Two Nodes? Exactly like in my example?
The problem that both Edges will overlap and you will no longer be able to identify the Edges >> Please check the below photo. 

![image](https://user-images.githubusercontent.com/17943997/122398700-3023fa00-cf8b-11eb-9714-f706b0ffe000.png)

**Comment by laimaretto** [comment]
Hi @Melzonko , good point ... I've seen this [here](https://github.com/WestHealth/pyvis/issues/51). If you want many links coming out of a node, then youl'll need the `directed` parameter.

I'm not sure then how to do it ... may be contacting some of the developers ...

**Comment by Melzonko** [comment]
@laimaretto Thanks a lot. Yes, I took my example from the same source. I will do so.

**Comment by Melzonko** [comment]
@boludo00  Hello Giancarlo, 
I saw your pull request "added check for bidirectional edge adding", is it helping in my case here? Hope you can support me in this.

from pyvis.network import Network
import networkx as nx
g = nx.MultiGraph()
g.add_node(0)
g.add_node(1)
g.add_edge(0, 1)
g.add_edge(0, 1)
nt = Network(directed=True)
nt.from_nx(g)
nt.set_edge_smooth('dynamic')

nt.set_options('''
var options = {
"edges": {
"arrowStrikethrough": false,
"color": {
"inherit": false
},
"font": {
"size": 10,
"align": "top"
},
"smooth": false
}
}
''')
nt.show('foo.html')

**Output is:**

![image](https://user-images.githubusercontent.com/17943997/122405359-0a99ef00-cf91-11eb-9740-f30515d1ed6a.png)


**But the target is:**


![image](https://user-images.githubusercontent.com/17943997/122405170-e1795e80-cf90-11eb-8b12-3844d860899c.png)

**Comment by IngoKl** [comment]
I have the same issue. After experimenting a little, I realized that you can remove `"arrows": "to"` from the edges in the generated JS object. It would be great if this could be set using `pyvis`. It seems impossible, even manually changing the edges, to remove/change this attribute from `pyvis`.

**Comment by oaayoub** [comment]
i still dont get it how to remove arrow heads in pyvis using custom arrow options

**Comment by afonsocrg** [comment]
@oaayoub I took a look into the source code and noticed that we could pass additional arguments when adding an edge:

```python
def add_edge(self, source, to, **options):
    # some verification and other code...
    if not edge_exists:
        e = Edge(source, to, self.directed, **options)
        self.edges.append(e.options)
```
And in Edge:
```python
class Edge(object):

    def __init__(self, source, dest, directed=False, **options):
        self.options = options
        # ...
        if directed:
        	if 'arrows' not in self.options: # <= note this line!
        		self.options["arrows"] = "to"
```

If you add edges with the `arrows` argument, you can control where the arrows are located!
```python
g.add_edge(src, dst, arrows = "any string other than 'to' 'from' and 'middle'")
```

I believe this is not the best solution, but after reading for a while, this was the only way I could hide arrows on a directed graph...
